"""add_day_type_to_leave_requests

Revision ID: 5466c0ef90d7
Revises: f8a4b2cd93e1
Create Date: 2026-03-06 11:59:16.575020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5466c0ef90d7'
down_revision = 'f8a4b2cd93e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('broadcasts', sa.Column('event_name', sa.String(length=200), nullable=True))
    op.add_column('broadcasts', sa.Column('event_time', sa.String(length=50), nullable=True))
    op.add_column('broadcasts', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('broadcasts', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('broadcasts', sa.Column('mentioned_employee_id', sa.Integer(), nullable=True))
    op.add_column('broadcasts', sa.Column('author_name', sa.String(length=100), nullable=True))
    op.add_column('broadcasts', sa.Column('author_email', sa.String(length=100), nullable=True))
    op.add_column('broadcasts', sa.Column('author_designation', sa.String(length=100), nullable=True))
    op.add_column('broadcasts', sa.Column('reactions_count', sa.Integer(), nullable=True))
    op.alter_column('broadcasts', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_foreign_key(None, 'broadcasts', 'users', ['mentioned_employee_id'], ['id'], ondelete='SET NULL')
    op.add_column('leave_requests', sa.Column('day_type', sa.Enum('full_day', 'half_day', name='day_type_enum'), nullable=False))
    op.alter_column('leave_requests', 'num_days',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('regularizations', sa.Column('approval_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regularizations', 'approval_reason')
    op.alter_column('leave_requests', 'num_days',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('leave_requests', 'day_type')
    op.drop_constraint(None, 'broadcasts', type_='foreignkey')
    op.alter_column('broadcasts', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('broadcasts', 'reactions_count')
    op.drop_column('broadcasts', 'author_designation')
    op.drop_column('broadcasts', 'author_email')
    op.drop_column('broadcasts', 'author_name')
    op.drop_column('broadcasts', 'mentioned_employee_id')
    op.drop_column('broadcasts', 'image_url')
    op.drop_column('broadcasts', 'event_type')
    op.drop_column('broadcasts', 'event_time')
    op.drop_column('broadcasts', 'event_name')
    op.drop_column('broadcasts', 'event_date')
    # ### end Alembic commands ###

