"""Add phone column

Revision ID: 6ddbb253a03a
Revises: d1ced7872509
Create Date: 2025-11-20 13:52:42.470134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ddbb253a03a'
down_revision = 'd1ced7872509'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Add phone column only if it doesn't already exist
    existing_columns = [row[0] for row in conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name='users' AND column_name='phone'"
    ))]
    if not existing_columns:
        op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))

    # Add unique constraint only if it doesn't already exist
    existing_constraints = [row[0] for row in conn.execute(sa.text(
        "SELECT conname FROM pg_constraint "
        "WHERE conrelid='users'::regclass AND contype='u'"
    ))]
    phone_constraint_exists = any('phone' in name for name in existing_constraints)
    if not phone_constraint_exists:
        op.create_unique_constraint('uq_users_phone', 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###

