"""Initial migration

Revision ID: d1ced7872509
Revises: 7a2edd681821
Create Date: 2025-11-18 17:48:58.414258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ced7872509'
down_revision = '7a2edd681821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

