"""Initial migration

Revision ID: 782d913da417
Revises: 
Create Date: 2025-12-03 12:44:24.082285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782d913da417'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_requests', 'num_days',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=3, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_requests', 'num_days',
               existing_type=sa.DECIMAL(precision=3, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
